config/routes.rb
Rails.application.routes.draw do
  resources :payments
  root 'payments#index'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/transaction.rb
require 'pagarme'
# example:
# PagarMe.api_key = "ak_test_Po52jGJ5XIWiutdmkZc7lpccveMUoh";
PagarMe.api_key = "your_api_key";
class Transaction < ActiveRecord::Base
  belongs_to :payment

  def self.save_transaction(payment)
    @transaction =  Transaction.new(
      amount: payment.price,
      card_hash: payment.card_hash,
      payment_id: payment.id
    )

    pagarme_transaction = PagarMe::Transaction.new(
      {
        amount: @transaction.amount,
        card_hash: @transaction.card_hash
      }
    )
    pagarme_transaction.charge

    @transaction.status = pagarme_transaction.status
    @transaction.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    respond_to do |format|
      if @payment.save
        Transaction.save_transaction(@payment)
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:card_number, :card_holder_name, :card_expiration_month, :card_expiration_year, :card_cvv, :card_hash, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4PagarMe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://pagar.me/assets/pagarme-v2.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_number %><br>
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_holder_name %><br>
    <%= f.text_field :card_holder_name %>
  </div>
  <div class="field">
    <%= f.label :card_expiration_month %><br>
    <%= f.text_field :card_expiration_month %>
  </div>
  <div class="field">
    <%= f.label :card_expiration_year %><br>
    <%= f.text_field :card_expiration_year %>
  </div>
  <div class="field">
    <%= f.label :card_cvv %><br>
    <%= f.text_field :card_cvv %>
  </div>
   <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div id="field_errors">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>Card number</th>
      <th>Card holder name</th>
      <th>Card expiration month</th>
      <th>Card expiration year</th>
      <th>Card cvv</th>
      <th>Card hash</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.card_number %></td>
        <td><%= payment.card_holder_name %></td>
        <td><%= payment.card_expiration_month %></td>
        <td><%= payment.card_expiration_year %></td>
        <td><%= payment.card_cvv %></td>
        <td><%= payment.card_hash %></td>
         <td><%= payment.price %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Card number:</strong>
  <%= @payment.card_number %>
</p>

<p>
  <strong>Card holder name:</strong>
  <%= @payment.card_holder_name %>
</p>

<p>
  <strong>Card expiration month:</strong>
  <%= @payment.card_expiration_month %>
</p>

<p>
  <strong>Card expiration year:</strong>
  <%= @payment.card_expiration_year %>
</p>

<p>
  <strong>Card cvv:</strong>
  <%= @payment.card_cvv %>
</p>

<p>
  <strong>Card hash:</strong>
  <%= @payment.card_hash %>
</p>

<p>
  <strong>Card hash:</strong>
  <%= @payment.price %>
</p>
<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>